[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10"
byte_set = "0.1"
anyhow = "1.0"
scan_fmt = "0.2"
slotmap = "1.0"
ndarray = "0.15"
take-until = "0.1"
hashbrown = "0.13"
glam = "0.22"
nom = "7.1"